apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rules
  - namespace.yaml
  - vl-cluster.yaml
  - vm-agent.yaml
  - vm-alert.yaml
  - vm-alertmanager.yaml
  - vm-cluster.yaml
  - vm-operator.yaml
  - vt-cluster.yaml
