---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: kubernetes
  namespace: observability
  labels:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  resyncPeriod: 0m
  allowCrossNamespaceImport: true
  instanceSelector: {}
  valuesFrom:
    - targetPath: jsonData.grafanaUsername
      valueFrom:
        secretKeyRef:
          key: GF_SECURITY_ADMIN_USER
          name: grafana-credentials
    - targetPath: secureJsonData.grafanaPassword
      valueFrom:
        secretKeyRef:
          key: GF_SECURITY_ADMIN_PASSWORD
          name: grafana-credentials
  datasource:
    name: Kubernetes
    type: ricoberger-kubernetes-datasource
    uid: kubernetes
    access: proxy
    isDefault: false
    orgId: 1
    editable: false
    jsonData:
      clusterProvider: incluster
      grafanaUsername: ${GF_SECURITY_ADMIN_USER}
      impersonateUser: true
      impersonateGroups: true
      generateKubeconfig: true
      generateKubeconfigName: homelab
      generateKubeconfigTTL: 604800
      generateKubeconfigPort: 11716
      generateKubeconfigRedirectUrls:
        - http://localhost:11716
      integrationsMetricsDatasourceUid: victoriametrics
      integrationsMetricsClusterLabel: ".*"
      integrationsMetricsLogs: |
        {
          "pod": {
            "datasource": {
              "type": "victoriametrics-logs-datasource",
              "uid": "victorialogs"
            },
            "queries": [
              {
                "refId": "A",
                "expr": "k8s.pod.name:=\"${pod}\" | sort by (_time) desc",
                "queryType": "instant",
                "maxLines": 1000
              }
            ]
          },
          "workload": {
            "datasource": {
              "type": "victoriametrics-logs-datasource",
              "uid": "victorialogs"
            },
            "queries": [
              {
                "refId": "A",
                "expr": "k8s.pod.name:in(${pod}) | sort by (_time) desc",
                "queryType": "instant",
                "maxLines": 1000
              }
            ]
          },
          "namespace": {
            "datasource": {
              "type": "victoriametrics-logs-datasource",
              "uid": "victorialogs"
            },
            "queries": [
              {
                "refId": "A",
                "expr": "k8s.namespace.name:=\"${namespace}\" | sort by (_time) desc",
                "queryType": "instant",
                "maxLines": 1000
              }
            ]
          },
          "node": {
            "datasource": {
              "type": "victoriametrics-logs-datasource",
              "uid": "victorialogs"
            },
            "queries": [
              {
                "refId": "A",
                "expr": "k8s.node.name:=\"${node}\" | sort by (_time) desc",
                "queryType": "instant",
                "maxLines": 1000
              }
            ]
          }
        }
      integrationsTracesQuery: '{"datasource":"victoriatraces","queries":[{"query":"$${__value.raw}","refId":"A"}]}'
    secureJsonData:
      grafanaPassword: ${GF_SECURITY_ADMIN_PASSWORD}
