{
 "title": "Vitess Misc",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "VTGate query cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vtgate_query_plan_cache_length" },
    {
     "expr": "vtgate_query_plan_cache_capacity"
    }
   ]
  },
  {
   "title": "VTTablet query cache",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vttablet_query_cache_length" },
    { "expr": "vttablet_query_cache_capacity" }
   ]
  },
  {
   "title": "VTGate health check connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vtgate_healthcheck_connections" }
   ]
  },
  {
   "title": "VTTablet health check errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vtgate_healthcheck_errors[1m])"
    }
   ]
  },
  {
   "title": "VTTablet external reparents",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_external_reparents_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet external reparent time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_external_reparents_sum[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet replication  lag",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vttablet_heartbeat_current_lag_ns"
    }
   ]
  },
  {
   "title": "VTTablet internal errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vttablet_internal_errors" }
   ]
  },
  {
   "title": "VTTablet heartbeat read errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_heartbeat_read_errors[1m])"
    }
   ]
  },
  {
   "title": "VTTablet heartbeat write errors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_heartbeat_write_errors[1m])"
    }
   ]
  }
 ]
}