{
 "title": "Vitess Queries",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "VTGate QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vtgate_api_count[1m])" }
   ]
  },
  {
   "title": "VTGate Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vtgate_api_sum[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet queries by plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_queries_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet latency by plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_queries_sum[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTGate Error rates",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vtgate_api_error_counts[1m])"
    }
   ]
  },
  {
   "title": "VTTablet Error rates",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vttablet_errors[1m])" }
   ]
  },
  {
   "title": "VTTablet MySQL QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vttablet_mysql_count[1m])" }
   ]
  },
  {
   "title": "VTTablet MySQL latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_mysql_sum[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet conn pool waits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_conn_pool_wait_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet conn pool wait time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_conn_pool_wait_time[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet conn pool",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vttablet_conn_pool_in_use" },
    { "expr": "vttablet_conn_pool_capacity" }
   ]
  },
  {
   "title": "VTTablet query kills",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_kills{query_type=\"Queries\"}[1m])"
    }
   ]
  },
  {
   "title": "VTTablet Consolidations",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vttablet_waits_count[1m])" }
   ]
  }
 ]
}