{
 "title": "Vitess query details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "VTTablet QPS by table and plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_query_counts[1m])"
    }
   ]
  },
  {
   "title": "VTTablet latency by table and plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_query_times_ns[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet row counts by table and plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_query_row_counts[1m])"
    }
   ]
  },
  {
   "title": "VTTablet error counts by table and plan",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_query_error_counts[1m])"
    }
   ]
  },
  {
   "title": "VTTablet QPS by table and user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_user_table_query_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet latency by table and user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_user_table_query_times_ns[1m])/1000000000"
    }
   ]
  }
 ]
}