{
 "title": "Vitess Transactions",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "VTTablet Transactions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_transactions_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet transaction time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_transactions_sum[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet transaction pool waits",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_transaction_pool_wait_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet transaction pool wait time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_transaction_pool_wait_time[1m])"
    }
   ]
  },
  {
   "title": "VTTablet Transactions by user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_user_transaction_count[1m])"
    }
   ]
  },
  {
   "title": "VTTablet transaction time by user",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_user_transaction_times_ns[1m])/1000000000"
    }
   ]
  },
  {
   "title": "VTTablet transaction kills",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_kills{query_type=\"Transactions\"}[1m])"
    }
   ]
  },
  {
   "title": "VTTablet transaction pool available",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vttablet_transaction_pool_in_use"
    },
    {
     "expr": "vttablet_transaction_pool_capacity"
    }
   ]
  }
 ]
}