---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitess-client
  namespace: vitess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitess-client
  template:
    metadata:
      labels:
        app: vitess-client
    spec:
      containers:
        - name: vitess-client
          args:
            - -address=user@tcp(example-vtgate-ae7df4b6:3306)/
            - -create-orders
            - -goroutines=100
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: registry.example.com/vitess:latest
          imagePullPolicy: Always
