storage:
  master:
    count: 1
    size: 10Gi
    storageClass: default-v2-xfs-noatime
  tserver:
    count: 1
    size: 10Gi
    storageClass: default-v2-xfs-noatime

resource:
  master:
    requests:
      cpu: "2"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  tserver:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 4Gi

replicas:
  master: 1
  tserver: 1
  totalMasters: 3

isMultiAz: True
AZ: germanywestcentral-3
masterAddresses: "yb-master-0.yb-masters.yb-germanywestcentral-1.svc.cluster.local:7100,yb-master-0.yb-masters.yb-germanywestcentral-2.svc.cluster.local:7100,yb-master-0.yb-masters.yb-germanywestcentral-3.svc.cluster.local:7100"

gflags:
  master:
    default_memory_limit_to_ram_ratio: 0.85
    placement_cloud: "azure"
    placement_region: "germanywestcentral"
    placement_zone: "germanywestcentral-3"
  tserver:
    placement_cloud: "azure"
    placement_region: "germanywestcentral"
    placement_zone: "germanywestcentral-3"

enableLoadBalancer: false
