---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: yugabytedb-yb-master
  namespace: yugabytedb
  labels:
    app: "yb-master"
    release: "yugabytedb"
    chart: "yugabyte"
    component: "yugabytedb"
spec:
  jobLabel: "yugabytedb-yb-master"
  selector:
    matchLabels:
      app: "yb-master"
      release: "yugabytedb"
      service-type: "headless"
  endpoints:
    - port: http-ui
      path: /prometheus-metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: "group"
          replacement: "yb-master"
        - targetLabel: "export_type"
          replacement: "master_export"
        - targetLabel: "node_prefix"
          replacement: "yugabytedb"
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
      metricRelabelConfigs:
        - regex: (.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: saved_name
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: server_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $2
          sourceLabels:
            - __name__
          targetLabel: service_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: $3
          sourceLabels:
            - __name__
          targetLabel: service_method
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: rpc_latency$4
          sourceLabels:
            - __name__
          targetLabel: __name__

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: yugabytedb-yb-tserver
  namespace: yugabytedb
  labels:
    app: "yb-tserver"
    release: "yugabytedb"
    chart: "yugabyte"
    component: "yugabytedb"
spec:
  jobLabel: "yugabytedb-yb-tserver"
  selector:
    matchLabels:
      app: "yb-tserver"
      release: "yugabytedb"
      service-type: "headless"
  endpoints:
    - port: http-ui
      path: /prometheus-metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: "group"
          replacement: "yb-tserver"
        - targetLabel: "export_type"
          replacement: "tserver_export"
        - targetLabel: "node_prefix"
          replacement: "yugabytedb"
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
      metricRelabelConfigs:
        - regex: (.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: saved_name
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: server_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $2
          sourceLabels:
            - __name__
          targetLabel: service_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: $3
          sourceLabels:
            - __name__
          targetLabel: service_method
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: rpc_latency$4
          sourceLabels:
            - __name__
          targetLabel: __name__
    - port: http-ycql-met
      path: /prometheus-metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: "group"
          replacement: "ycql"
        - targetLabel: "export_type"
          replacement: "cql_export"
        - targetLabel: "node_prefix"
          replacement: "yugabytedb"
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
      metricRelabelConfigs:
        - regex: (.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: saved_name
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: server_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $2
          sourceLabels:
            - __name__
          targetLabel: service_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: $3
          sourceLabels:
            - __name__
          targetLabel: service_method
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: rpc_latency$4
          sourceLabels:
            - __name__
          targetLabel: __name__
    - port: http-ysql-met
      path: /prometheus-metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: "group"
          replacement: "ysql"
        - targetLabel: "export_type"
          replacement: "ysql_export"
        - targetLabel: "node_prefix"
          replacement: "yugabytedb"
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: instance
      metricRelabelConfigs:
        - regex: (.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: saved_name
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $1
          sourceLabels:
            - __name__
          targetLabel: server_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
          replacement: $2
          sourceLabels:
            - __name__
          targetLabel: service_type
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: $3
          sourceLabels:
            - __name__
          targetLabel: service_method
        - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
          replacement: rpc_latency$4
          sourceLabels:
            - __name__
          targetLabel: __name__
    # - port: http-yedis-met
    #   path: /prometheus-metrics
    #   interval: 30s
    #   relabelConfigs:
    #     - targetLabel: "group"
    #       replacement: "yedis"
    #     - targetLabel: "export_type"
    #       replacement: "redis_export"
    #     - targetLabel: "node_prefix"
    #       replacement: "yugabytedb"
    #     - action: replace
    #       sourceLabels:
    #         - __meta_kubernetes_pod_name
    #       targetLabel: instance
    #   metricRelabelConfigs:
    #     - regex: (.*)
    #       replacement: $1
    #       sourceLabels:
    #         - __name__
    #       targetLabel: saved_name
    #     - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
    #       replacement: $1
    #       sourceLabels:
    #         - __name__
    #       targetLabel: server_type
    #     - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)
    #       replacement: $2
    #       sourceLabels:
    #         - __name__
    #       targetLabel: service_type
    #     - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
    #       replacement: $3
    #       sourceLabels:
    #         - __name__
    #       targetLabel: service_method
    #     - regex: handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?
    #       replacement: rpc_latency$4
    #       sourceLabels:
    #         - __name__
    #       targetLabel: __name__
