storage:
  master:
    count: 1
    size: 10Gi
  tserver:
    count: 1
    size: 10Gi

resource:
  master:
    requests:
      cpu: "2"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  tserver:
    requests:
      cpu: "4"
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 4Gi

replicas:
  master: 3
  tserver: 3

gflags:
  master:
    default_memory_limit_to_ram_ratio: 0.85
  tserver: {}

enableLoadBalancer: false

authCredentials:
  ysql:
    password: "mypassword"
  ycql:
    password: "mypassword"
