---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugabytedb-client
  namespace: yugabytedb
spec:
  replicas: 20
  selector:
    matchLabels:
      app: yugabytedb-client
  template:
    metadata:
      labels:
        app: yugabytedb-client
    spec:
      containers:
        - name: yugabytedb-client
          args:
            - -connection-string=postgres://commerceuser:commercepassword@yb-tserver-0.yb-tservers.yugabytedb.svc.cluster.local:5433,yb-tserver-1.yb-tservers.yugabytedb.svc.cluster.local:5433,yb-tserver-2.yb-tservers.yugabytedb.svc.cluster.local:5433/commerce?load_balance=true
            - -create-orders
            - -goroutines=100
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: registry.homelab.ricoberger.dev/yugabytedb-client:latest
          imagePullPolicy: Always
