name: registry

services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    networks:
      - proxy
    volumes:
      - ./data:/var/lib/registry
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`registry.homelab.ricoberger.dev`)"
      - "traefik.http.routers.registry.entrypoints=https"
      - "traefik.http.routers.registry.tls=true"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"

networks:
  proxy:
    external: true
